# Generated by Django 2.2.7 on 2019-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('manager', 'Организатор мероприятия'), ('client', 'Заказчик'), ('editor', 'Музыкальный редактор')], max_length=20),
        ),
    ]
