# Generated by Django 2.2.7 on 2019-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191118_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bio',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
