# Generated by Django 2.2.7 on 2019-11-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_editor_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('processing', 'В обработке'), ('confirmed', 'Подтверждена')], max_length=20)),
                ('music', models.TextField()),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
