# Generated by Django 2.2.7 on 2019-11-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
    ]
