# Generated by Django 2.2.7 on 2019-11-19 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191118_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Artist', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='file_name',
            field=models.CharField(default='file', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SongRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Запрос отправлен'), ('processing', 'В обработке'), ('confirmed', 'Подтверждено')], max_length=20)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Song')),
            ],
        ),
    ]
