# Generated by Django 2.2.7 on 2019-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191119_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'заказчика', 'verbose_name_plural': 'заказчики'},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': 'редактора', 'verbose_name_plural': 'редакторы'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'организатора', 'verbose_name_plural': 'организаторы'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'музыкальную композицию', 'verbose_name_plural': 'музыкальные композиции'},
        ),
        migrations.RemoveField(
            model_name='songrights',
            name='song',
        ),
        migrations.AddField(
            model_name='songrights',
            name='artist',
            field=models.CharField(default='Artist', max_length=20, verbose_name='Исполнитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songrights',
            name='name',
            field=models.CharField(default='Name', max_length=20, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='event',
            name='songs',
            field=models.ManyToManyField(to='core.Song'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='staff_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер сотрудника'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=20, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_name',
            field=models.CharField(max_length=50, verbose_name='Название музыкального файла'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
