# Generated by Django 2.2.7 on 2019-11-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191119_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='songrights',
            options={'verbose_name': 'права на композицию', 'verbose_name_plural': 'права на композицию'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Request', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='songs',
            field=models.ManyToManyField(to='core.Song', verbose_name='Список музыкальных композиций'),
        ),
        migrations.AlterField(
            model_name='songrights',
            name='organization',
            field=models.CharField(max_length=50, verbose_name='Организация'),
        ),
    ]
